name: Docs

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Docs UniTool project
    runs-on: macos-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      # Install DocFx
      - name: Install
        run: |
          brew install mono
          brew install docfx
      
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.7f1
      
      # Build
      - name: Build
        run: |
          docfx .docs/docfx.json
      
      # Upload
      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: .docs/_site
