name: Docs

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Docs UniTool project
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Install Node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      # Install DocFx
      - name: Install
        run: |
          choco install -y docfx
      
      # Build
      - name: Build
        run: |
          cd .docs
          mkdir src
          copy ..\UniTool.csproj src\UniTool.csproj
          xcopy /e /i /y ..\Assets src\Assets\ 
          docfx metadata
          docfx build
      
      # Upload
      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: .docs/_site
      
      # Deploy Netlify
      - name: Deploy to netlify
        run: |
          npm install netlify-cli
          npx netlify-cli deploy --dir=.docs/_site --message="update UniTool."　2> deploy.log
          set DEPLOY_URL=`findstr "Website Draft URL" deploy.log`
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          
      # Comment
      - uses: actions/github-script@0.8.0
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deploy Completed.\n ${{ DEPLOY_URL }}'
            })
