name: Actions 😎

on:
  pull_request: {}
  push: { branches: [master, develop] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Test UniTool project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.7f1
          customParameters: -enableCodeCoverage
          testMode: playmode
                
      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.7f1
          customParameters: -enableCodeCoverage
          testMode: editmode

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: TestResults
          path: artifacts
         
      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: CodeCoverage
          path: CodeCoverage
          
      - uses: IgnusG/jest-report-action@v2.3.3
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          junit-file: artifacts/playmode-results.xml
      
      - name: Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/EditMode/TestCoverageResults_0000.xml
          
      - name: Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/PlayMode/TestCoverageResults_0000.xml
